In [43]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

import pandas as pd


Se usara y ver la base de datos principales

In [44]:
# La base de datos de la encuesta de la vendimia, son los datos de los encuestados de algunos visitantes de la vendimia
# que fue realizada por la municipalidad y ese encuentra  vienen en un excel en diferentes hojas, entonces se guardo la hoja que se va a usar en .csv.
# que quedo y se llamo poblacionporedad.
# link de acceso: https://drive.google.com/file/d/1VGLZvZ4OsOEGJc1RinLuy8iJz2aOMo-s/view

file_id_encuesta = "1VGLZvZ4OsOEGJc1RinLuy8iJz2aOMo-s"

url = f"https://drive.google.com/uc?id={file_id_encuesta}"

vendimia = pd.read_csv(
    url,
    sep=";",
    engine="python"
)

#Se va a ver como es la tabla con los 20 primeras filas
vendimia.head(20)

,Marca temporal,¿Cuál es su edad?,¿Con qué género se identifica usted?,¿En qué comuna reside actualmente?,Alojamiento y estadía,Responda esta pregunta solo si en la anterior seleccionó “Sí”.,¿Qué tipo de alojamiento utilizó?,Transporte: $,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
0,05-02-2025 18:50,58,NaN,San Fernando,No,0,Casa propia,0,0,5000,5000,5,5,5,1,5,5
1,05-02-2025 18:55,16,NaN,San Fernando,No,0,Casa,0,0,5000,9000,4,4,4,5,5,4
2,05-02-2025 19:02,63,NaN,Coquimbo,Sí,3,Casa de amigos o familiares,100000,0,0,100000,5,5,5,5,5,5
3,05-02-2025 19:04,23,NaN,Coltauco,No,0,Vienen por el dia,8000,0,60000,50000,5,5,5,1,3,4
4,05-02-2025 19:06,46,NaN,La cruz,No,0,Viaje,100000,0,50000,50000,5,5,5,3,5,5
5,05-02-2025 19:07,13,NaN,Coltauco,No,0,Vienen por el dia,10000,0,60000,30000,5,5,5,3,3,3
6,05-02-2025 19:08,39,NaN,Mostazal,No,0,Viajando,50000,0,50000,50000,5,5,5,3,5,5
7,05-02-2025 19:09,37,NaN,San Fernando,No,0,Casa propia,30000,0,10000,0,5,5,5,5,5,5
8,05-02-2025 19:11,35,NaN,Metropolitana,No,0,Viaje,Viaje,0,40000,15000,5,5,5,3,2,5
9,05-02-2025 19:13,46,NaN,Metropolitana,No,0,Viaje,15000,0,45000,15000,5,5,5,3,2,5
10,05-02-2025 19:13,24,NaN,Antofagasta,No,0,Dia,12000,0,12000,30000,5,5,5,3,5,5
11,05-02-2025 19:13,38,NaN,San Fernando,No,0,Casa propia,5000,0,25000,30000,5,5,5,1,5,4
12,05-02-2025 19:18,58,NaN,Tinguiririca,No,0,Casa propia,2000,0,5000,0,5,5,5,3,3,5
13,05-02-2025 19:20,41,NaN,San Fernando,No,0,Casa propia,0,0,10000,13000,5,5,5,5,5,5
14,05-02-2025 19:21,48,NaN,San Fernando,No,0,Casa propia,10000,0,35000,20000,5,5,5,3,5,3
15,05-02-2025 19:21,69,NaN,San Fernando,No,0,Casa propia,0,0,0,0,5,5,5,3,3,5
16,05-02-2025 19:23,61,NaN,San Fernando,No,0,Casa propia,0,0,10000,10000,5,5,5,2,2,5
17,05-02-2025 19:24,35,NaN,Placilla,No,0,Casa propia,10000,0,30000,30000,5,5,5,4,3,5
18,05-02-2025 19:29,46,NaN,Santiago,Sí,1,Cabaña/Airbnb,40000,70000,30000,40000,3,3,4,4,1,5
19,05-02-2025 19:29,29,NaN,Santiago,Sí,"2,77",Hotel/Hostal,20000,300000,50000,100000,5,5,2,5,2,3

In [45]:
#Saber cuáles son las columnas
print (vendimia.columns.tolist())

['Marca temporal', '  ¿Cuál es su edad?  ', '¿Con qué género se identifica usted?  ', '  ¿En qué comuna reside actualmente?  ', '  Alojamiento y estadía  ', 'Responda esta pregunta solo si en la anterior seleccionó “Sí”.  ', '¿Qué tipo de alojamiento utilizó?  ', 'Transporte: $  ', 'Alojamiento: $  ', 'Alimentación: $  ', 'Compras (vino, recuerdos, artesanías): $  ', 'Seguridad ', 'Limpieza  ', 'Comodidad  ', 'Programación artística  ', 'Acceso a baños  ', '¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"? ']

In [46]:
#Se tiene que saber cuantas filas y columnas hay, la primera es para saber si estan todos los datos
vendimia.shape

(390, 17)

In [47]:
#Para saber la informacion de la tabla, cual es su formato, si tiene datos nulos, entre otros.
vendimia.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 17 columns):
 #   Column                                                                                               Non-Null Count  Dtype
---  ------                                                                                               --------------  -----
 0   Marca temporal                                                                                       390 non-null    str
 1     ¿Cuál es su edad?                                                                                  390 non-null    int64
 2   ¿Con qué género se identifica usted?                                                                 0 non-null      float64
 3     ¿En qué comuna reside actualmente?                                                                 390 non-null    str
 4     Alojamiento y estadía                                                                              390 non-null    str
 5   Responda esta pregunta solo si en la anterior seleccionó “Sí”.                                       390 non-null    str
 6   ¿Qué tipo de alojamiento utilizó?                                                                    390 non-null    str
 7   Transporte: $                                                                                        390 non-null    str
 8   Alojamiento: $                                                                                       390 non-null    int64
 9   Alimentación: $                                                                                      390 non-null    int64
 10  Compras (vino, recuerdos, artesanías): $                                                             390 non-null    int64
 11  Seguridad                                                                                            390 non-null    int64
 12  Limpieza                                                                                             390 non-null    int64
 13  Comodidad                                                                                            390 non-null    int64
 14  Programación artística                                                                               390 non-null    int64
 15  Acceso a baños                                                                                       390 non-null    int64
 16  ¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?   390 non-null    int64
dtypes: float64(1), int64(10), str(6)
memory usage: 51.9 KB

Del info, estas son textos:
- En qué comuna reside actualmente?: esta bien que sea texto, hay que arreglar los textos. 
- Alojamiento y estadía: pregunta de si y no, esta bien que sea texto
- Responda esta pregunta solo si en la anterior seleccionó “Sí”: Es dias, tiene que ser numero.
- ¿Qué tipo de alojamiento utilizó?: Texto, o agrupar 
- Transporte: Son valores, entonces esto indica que hay palabras

In [48]:
#Primero hay que eliminar los espacios que sobran de los nombres de la columna
vendimia.columns = vendimia.columns.str.strip()
vendimia.columns.tolist()

['Marca temporal',
 '¿Cuál es su edad?',
 '¿Con qué género se identifica usted?',
 '¿En qué comuna reside actualmente?',
 'Alojamiento y estadía',
 'Responda esta pregunta solo si en la anterior seleccionó “Sí”.',
 '¿Qué tipo de alojamiento utilizó?',
 'Transporte: $',
 'Alojamiento: $',
 'Alimentación: $',
 'Compras (vino, recuerdos, artesanías): $',
 'Seguridad',
 'Limpieza',
 'Comodidad',
 'Programación artística',
 'Acceso a baños',
 '¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?']

In [49]:
#Como se ven las ultimas 10 filas
vendimia.tail(10)

,Marca temporal,¿Cuál es su edad?,¿Con qué género se identifica usted?,¿En qué comuna reside actualmente?,Alojamiento y estadía,Responda esta pregunta solo si en la anterior seleccionó “Sí”.,¿Qué tipo de alojamiento utilizó?,Transporte: $,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
380,05-04-2025 18:57,50,NaN,San Fernando,No,0,Casa de amigos o familiares,10000,0,30000,45000,5,5,5,3,3,5
381,05-04-2025 18:58,43,NaN,San Fernando,Sí,"2,77",Casa de amigos o familiares,2200,0,45000,35000,5,5,4,3,1,5
382,05-04-2025 18:59,19,NaN,San Fernando,No,0,Casa de amigos o familiares,3000,0,6000,5000,5,5,4,4,4,4
383,05-04-2025 19:00,56,NaN,Santa Cruz,Sí,"2,77",Casa de amigos o familiares,5000,0,56000,95000,5,3,5,5,1,5
384,05-04-2025 19:02,70,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,5000,0,5,5,5,4,3,5
385,05-04-2025 19:02,62,NaN,San Fernando,No,0,Casa de amigos o familiares,5000,0,25000,0,5,4,5,4,4,4
386,05-04-2025 19:03,30,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,2000,10000,5,5,4,3,3,5
387,05-04-2025 19:09,37,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,20000,15000,5,4,4,1,1,5
388,05-04-2025 19:11,27,NaN,San Fernando,No,0,Casa de amigos o familiares,5000,0,10000,0,5,4,4,3,3,5
389,05-04-2025 19:12,30,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,20000,0,5,5,3,3,5,5

In [50]:
#Saber cuantos datos hay nulos
vendimia.isnull().sum()

Marca temporal                                                                                          0
¿Cuál es su edad?                                                                                       0
¿Con qué género se identifica usted?                                                                  390
¿En qué comuna reside actualmente?                                                                      0
Alojamiento y estadía                                                                                   0
Responda esta pregunta solo si en la anterior seleccionó “Sí”.                                          0
¿Qué tipo de alojamiento utilizó?                                                                       0
Transporte: $                                                                                           0
Alojamiento: $                                                                                          0
Alimentación: $                                                                                         0
Compras (vino, recuerdos, artesanías): $                                                                0
Seguridad                                                                                               0
Limpieza                                                                                                0
Comodidad                                                                                               0
Programación artística                                                                                  0
Acceso a baños                                                                                          0
¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?      0
dtype: int64

In [51]:
# La columna de genero tiene 390 nulos, significa que nadie respondio, entonces se elimina
vendimia = vendimia.drop(columns=["¿Con qué género se identifica usted?"])

In [52]:
# Ver si hay duplicados en la tabla
vendimia.duplicated().sum()

np.int64(0)

In [53]:
#Revisar codigos especiale ssi se encuentran.
(vendimia == 999).sum().sum()

(vendimia == -1).sum().sum()

np.int64(0)

In [54]:
#Se realiza un describe para ver si hay datos raros.  
vendimia.describe()

,¿Cuál es su edad?,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
count,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000
mean,38.812821,4197.435897,25587.179487,22720.512821,4.800000,4.743590,4.512821,3.502564,3.407692,4.884615
std,14.136621,36417.523023,26408.912956,23601.475701,0.574523,0.642054,0.865559,1.321658,1.485298,0.526441
min,13.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,27.000000,0.000000,10000.000000,10000.000000,5.000000,5.000000,4.000000,3.000000,2.000000,5.000000
50%,38.000000,0.000000,20000.000000,20000.000000,5.000000,5.000000,5.000000,4.000000,4.000000,5.000000
75%,49.000000,0.000000,30000.000000,30000.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
max,78.000000,500000.000000,220000.000000,250000.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

Con el describe, nos damos cuenta que los valores de evaluacion esta en los valores minimos y maximos correctos, que son 0 y 5, respectivamente. Y a su vez se observa que la edad de los asistentes fueron entre 13 y 78 años.

In [55]:
#Ahora se limpia la columna de comunas donde reside
vendimia["¿En qué comuna reside actualmente?"].value_counts()

¿En qué comuna reside actualmente?
San Fernando        267
Santiago             17
Rancagua             11
Chimbarongo          10
Santa Cruz            8
Chimbarongo           5
Santiago              4
Rengo                 4
La Florida            4
Placilla              3
Nancagua              3
Metropolitana         2
Tinguiririca          2
Las condes            2
Talca                 2
San vicente           2
Curico                2
Providencia           2
Coquimbo              1
Coltauco              1
La cruz               1
Coltauco              1
Mostazal              1
Antofagasta           1
Santa Cruz            1
Lo barnechea          1
Pinto                 1
Marchigue             1
La Florida            1
San Bernardo          1
Maipu                 1
Estación central      1
Peñaloren             1
Doñihue               1
Talgante              1
Machali               1
Pichilemu             1
Limache               1
San juaquin           1
Graneros              1
Graneros              1
San miguel            1
Puente alto           1
Puente varas          1
Quilicura             1
Talagante             1
La florida            1
Renca                 1
Rancagua              1
San Vicente           1
Romeral               1
Chepica               1
Requinua              1
Peñalolen             1
Las cabras            1
Nancagua              1
Malloa                1
Iquique               1
Name: count, dtype: int64

In [56]:
#Eliminar los espacion de las comunas donde recide actualmente 
vendimia["¿En qué comuna reside actualmente?"] = (vendimia["¿En qué comuna reside actualmente?"]
.str.strip()
.str.title())

In [57]:
#Ver como la cuenta de la comuna que quedo despues de la eliminacion
vendimia["¿En qué comuna reside actualmente?"].value_counts()

¿En qué comuna reside actualmente?
San Fernando        267
Santiago             21
Chimbarongo          15
Rancagua             12
Santa Cruz            9
La Florida            6
Nancagua              4
Rengo                 4
Placilla              3
San Vicente           3
Coltauco              2
Metropolitana         2
Tinguiririca          2
Las Condes            2
Talca                 2
Curico                2
Providencia           2
Graneros              2
Coquimbo              1
La Cruz               1
Mostazal              1
Antofagasta           1
Lo Barnechea          1
Pinto                 1
Marchigue             1
San Bernardo          1
Maipu                 1
Estación Central      1
Peñaloren             1
Doñihue               1
Talgante              1
Machali               1
Pichilemu             1
Limache               1
San Juaquin           1
San Miguel            1
Puente Alto           1
Puente Varas          1
Quilicura             1
Talagante             1
Renca                 1
Romeral               1
Chepica               1
Requinua              1
Peñalolen             1
Las Cabras            1
Malloa                1
Iquique               1
Name: count, dtype: int64

In [58]:
#Como era un dato de texto y ver los datos
vendimia["Alojamiento y estadía"].value_counts()

Alojamiento y estadía
No    353
Sí     37
Name: count, dtype: int64

In [59]:
#Se cambio el nombre de la columna "Responda esta pregunta solo si en la anterior seleccionó “Sí”." a Dias_alojamiento para
#que se entienda lo que es.
vendimia = vendimia.rename(columns={"Responda esta pregunta solo si en la anterior seleccionó “Sí”.":
'Dias_Alojamiento'})
vendimia["Dias_Alojamiento"].value_counts()

Dias_Alojamiento
0       353
3        10
2         8
1         7
2,77      6
7         2
4         2
6         1
5         1
Name: count, dtype: int64

El 2,77 es el promedio, que ya venia de esta manera los datos, y son los que si se alojaron, y no pusieron un valor.

In [60]:
#Como se ve en la info, los datos de alojamiento son texto, y por eso lo cambiaremos a numero
vendimia["Dias_Alojamiento"] = (vendimia["Dias_Alojamiento"].astype(str).str.replace(",", ".", regex=False))
vendimia["Dias_Alojamiento"] = pd.to_numeric(vendimia["Dias_Alojamiento"], errors="coerce")

vendimia["Dias_Alojamiento"].dtype

dtype('float64')

In [ ]:
#Como se ve la info, ¿Qué tipo de alojamiento utilizó?" son textos, primero se cambio el nombre para trabajar
#de mejor manera a 'Tipo_Alojamiento', y agruparlas las que significan lo mismo y se escriben distintos.
vendimia = vendimia.rename(columns={"¿Qué tipo de alojamiento utilizó?":
'Tipo_Alojamiento'})
vendimia["Tipo_Alojamiento"].value_counts()

Tipo_Alojamiento
Casa de amigos o familiares    248
Casa propia                     69
Viaje                           36
Viaje                           11
Cabaña/Airbnb                    5
Viene por el dia                 4
Casa propia                      3
Hotel/Hostal                     3
Vienen por el dia                2
Viene por el día                 2
Casa                             1
Viajando                         1
Dia                              1
Familia                          1
Casas propia                     1
Casa Propia                      1
Viene por el día                 1
Name: count, dtype: int64

In [ ]:
#Primero se elimina los espacios de antes y despues de la variable
vendimia["Tipo_Alojamiento"] = (vendimia["Tipo_Alojamiento"].str.strip().str.lower())
vendimia["Tipo_Alojamiento"].value_counts()

Tipo_Alojamiento
casa de amigos o familiares    248
casa propia                     73
viaje                           47
cabaña/airbnb                    5
viene por el dia                 4
hotel/hostal                     3
viene por el día                 3
vienen por el dia                2
casa                             1
viajando                         1
dia                              1
familia                          1
casas propia                     1
Name: count, dtype: int64

In [ ]:
#Se agrupan los nombres, se realiza una variable de reemplazos y se pasa a .replace
reemplazos = {"casa de amigos o familiares": "Casa de amigos o familiares", "familia": "Casa de amigos o familiares","viaje": "Por el día","viajando": "Por el día","dia": "Por el día","viene por el dia": "Por el día","vienen por el dia": "Por el día","viene por el día": "Por el día","vienen por el día": "Por el día","casa propia": "Casa propia","casas propia": "Casa propia","casa": "Casa propia","hotel/hostal": "Alojamiento turístico","cabaña/airbnb": "Alojamiento turístico"}

vendimia["Tipo_Alojamiento"] = (vendimia["Tipo_Alojamiento"].replace(reemplazos))

In [ ]:
#Se hace el conteo para ver si esta bien los nombres y conteos
vendimia["Tipo_Alojamiento"].value_counts()

Tipo_Alojamiento
Casa de amigos o familiares    249
Casa propia                     75
Por el día                      58
Alojamiento turístico            8
Name: count, dtype: int64

In [ ]:
#En transporte hay un problema que es tipo texto y tiene que ser numero 
vendimia["Transporte: $"].value_counts().head(30)

Transporte: $
0         134
2000       48
5000       43
10000      23
20000      17
3000       16
1000       12
15000      11
2200        9
30000       8
4000        8
25000       7
8000        5
50000       5
12000       5
7000        5
40000       3
2300        3
1100        3
100000      2
6000        2
9000        2
14000       2
4800        2
Viaje       1
1200        1
8800        1
65000       1
150000      1
500         1
Name: count, dtype: int64

In [ ]:
#Ver los que son textos
vendimia[~vendimia["Transporte: $"].astype(str).str.replace(",", "").str.isnumeric()]["Transporte: $"].value_counts()

Transporte: $
Viaje     1
Name: count, dtype: int64

In [ ]:
# Ver si hay algun numero nulo
vendimia["Transporte: $"] = pd.to_numeric(vendimia["Transporte: $"],errors="coerce")
vendimia["Transporte: $"].isna().sum()

np.int64(1)

In [70]:
vendimia[vendimia["Transporte: $"].isna()]

,Marca temporal,¿Cuál es su edad?,¿En qué comuna reside actualmente?,Alojamiento y estadía,Dias_Alojamiento,Tipo_Alojamiento,Transporte: $,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
8,05-02-2025 19:11,35,Metropolitana,No,0.0,Por el día,NaN,0,40000,15000,5,5,5,3,2,5

<bound method Series.info of 0           0.0
1           0.0
2      100000.0
3        8000.0
4      100000.0
         ...
385      5000.0
386         0.0
387         0.0
388      5000.0
389         0.0
Name: Transporte: $, Length: 390, dtype: float64>