In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

import pandas as pd


Se usara y ver la base de datos principales

In [2]:
file_id_encuesta = "1VGLZvZ4OsOEGJc1RinLuy8iJz2aOMo-s"

url = f"https://drive.google.com/uc?id={file_id_encuesta}"

vendimia = pd.read_csv(
    url,
    sep=";",
    engine="python"
)

vendimia.head(20)

,Marca temporal,¿Cuál es su edad?,¿Con qué género se identifica usted?,¿En qué comuna reside actualmente?,Alojamiento y estadía,Responda esta pregunta solo si en la anterior seleccionó “Sí”.,¿Qué tipo de alojamiento utilizó?,Transporte: $,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
0,05-02-2025 18:50,58,NaN,San Fernando,No,0,Casa propia,0,0,5000,5000,5,5,5,1,5,5
1,05-02-2025 18:55,16,NaN,San Fernando,No,0,Casa,0,0,5000,9000,4,4,4,5,5,4
2,05-02-2025 19:02,63,NaN,Coquimbo,Sí,3,Casa de amigos o familiares,100000,0,0,100000,5,5,5,5,5,5
3,05-02-2025 19:04,23,NaN,Coltauco,No,0,Vienen por el dia,8000,0,60000,50000,5,5,5,1,3,4
4,05-02-2025 19:06,46,NaN,La cruz,No,0,Viaje,100000,0,50000,50000,5,5,5,3,5,5
5,05-02-2025 19:07,13,NaN,Coltauco,No,0,Vienen por el dia,10000,0,60000,30000,5,5,5,3,3,3
6,05-02-2025 19:08,39,NaN,Mostazal,No,0,Viajando,50000,0,50000,50000,5,5,5,3,5,5
7,05-02-2025 19:09,37,NaN,San Fernando,No,0,Casa propia,30000,0,10000,0,5,5,5,5,5,5
8,05-02-2025 19:11,35,NaN,Metropolitana,No,0,Viaje,Viaje,0,40000,15000,5,5,5,3,2,5
9,05-02-2025 19:13,46,NaN,Metropolitana,No,0,Viaje,15000,0,45000,15000,5,5,5,3,2,5
10,05-02-2025 19:13,24,NaN,Antofagasta,No,0,Dia,12000,0,12000,30000,5,5,5,3,5,5
11,05-02-2025 19:13,38,NaN,San Fernando,No,0,Casa propia,5000,0,25000,30000,5,5,5,1,5,4
12,05-02-2025 19:18,58,NaN,Tinguiririca,No,0,Casa propia,2000,0,5000,0,5,5,5,3,3,5
13,05-02-2025 19:20,41,NaN,San Fernando,No,0,Casa propia,0,0,10000,13000,5,5,5,5,5,5
14,05-02-2025 19:21,48,NaN,San Fernando,No,0,Casa propia,10000,0,35000,20000,5,5,5,3,5,3
15,05-02-2025 19:21,69,NaN,San Fernando,No,0,Casa propia,0,0,0,0,5,5,5,3,3,5
16,05-02-2025 19:23,61,NaN,San Fernando,No,0,Casa propia,0,0,10000,10000,5,5,5,2,2,5
17,05-02-2025 19:24,35,NaN,Placilla,No,0,Casa propia,10000,0,30000,30000,5,5,5,4,3,5
18,05-02-2025 19:29,46,NaN,Santiago,Sí,1,Cabaña/Airbnb,40000,70000,30000,40000,3,3,4,4,1,5
19,05-02-2025 19:29,29,NaN,Santiago,Sí,"2,77",Hotel/Hostal,20000,300000,50000,100000,5,5,2,5,2,3

In [152]:
print (vendimia.columns.tolist())

['Marca temporal', '  ¿Cuál es su edad?  ', '¿Con qué género se identifica usted?  ', '  ¿En qué comuna reside actualmente?  ', '  Alojamiento y estadía  ', 'Responda esta pregunta solo si en la anterior seleccionó “Sí”.  ', '¿Qué tipo de alojamiento utilizó?  ', 'Transporte: $  ', 'Alojamiento: $  ', 'Alimentación: $  ', 'Compras (vino, recuerdos, artesanías): $  ', 'Seguridad ', 'Limpieza  ', 'Comodidad  ', 'Programación artística  ', 'Acceso a baños  ', '¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"? ']

In [153]:
vendimia.shape

(390, 17)

In [154]:
vendimia.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 17 columns):
 #   Column                                                                                               Non-Null Count  Dtype
---  ------                                                                                               --------------  -----
 0   Marca temporal                                                                                       390 non-null    str
 1     ¿Cuál es su edad?                                                                                  390 non-null    int64
 2   ¿Con qué género se identifica usted?                                                                 0 non-null      float64
 3     ¿En qué comuna reside actualmente?                                                                 390 non-null    str
 4     Alojamiento y estadía                                                                              390 non-null    str
 5   Responda esta pregunta solo si en la anterior seleccionó “Sí”.                                       390 non-null    str
 6   ¿Qué tipo de alojamiento utilizó?                                                                    390 non-null    str
 7   Transporte: $                                                                                        390 non-null    str
 8   Alojamiento: $                                                                                       390 non-null    int64
 9   Alimentación: $                                                                                      390 non-null    int64
 10  Compras (vino, recuerdos, artesanías): $                                                             390 non-null    int64
 11  Seguridad                                                                                            390 non-null    int64
 12  Limpieza                                                                                             390 non-null    int64
 13  Comodidad                                                                                            390 non-null    int64
 14  Programación artística                                                                               390 non-null    int64
 15  Acceso a baños                                                                                       390 non-null    int64
 16  ¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?   390 non-null    int64
dtypes: float64(1), int64(10), str(6)
memory usage: 51.9 KB

In [155]:
vendimia.columns = vendimia.columns.str.strip()
vendimia.columns.tolist()

['Marca temporal',
 '¿Cuál es su edad?',
 '¿Con qué género se identifica usted?',
 '¿En qué comuna reside actualmente?',
 'Alojamiento y estadía',
 'Responda esta pregunta solo si en la anterior seleccionó “Sí”.',
 '¿Qué tipo de alojamiento utilizó?',
 'Transporte: $',
 'Alojamiento: $',
 'Alimentación: $',
 'Compras (vino, recuerdos, artesanías): $',
 'Seguridad',
 'Limpieza',
 'Comodidad',
 'Programación artística',
 'Acceso a baños',
 '¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?']

In [156]:
vendimia.tail(10)

,Marca temporal,¿Cuál es su edad?,¿Con qué género se identifica usted?,¿En qué comuna reside actualmente?,Alojamiento y estadía,Responda esta pregunta solo si en la anterior seleccionó “Sí”.,¿Qué tipo de alojamiento utilizó?,Transporte: $,Alojamiento: $,Alimentación: $,"Compras (vino, recuerdos, artesanías): $",Seguridad,Limpieza,Comodidad,Programación artística,Acceso a baños,"¿Estás de acuerdo con la afirmación: ""La Vendimia refuerza la identidad cultural de San Fernando""?"
380,05-04-2025 18:57,50,NaN,San Fernando,No,0,Casa de amigos o familiares,10000,0,30000,45000,5,5,5,3,3,5
381,05-04-2025 18:58,43,NaN,San Fernando,Sí,"2,77",Casa de amigos o familiares,2200,0,45000,35000,5,5,4,3,1,5
382,05-04-2025 18:59,19,NaN,San Fernando,No,0,Casa de amigos o familiares,3000,0,6000,5000,5,5,4,4,4,4
383,05-04-2025 19:00,56,NaN,Santa Cruz,Sí,"2,77",Casa de amigos o familiares,5000,0,56000,95000,5,3,5,5,1,5
384,05-04-2025 19:02,70,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,5000,0,5,5,5,4,3,5
385,05-04-2025 19:02,62,NaN,San Fernando,No,0,Casa de amigos o familiares,5000,0,25000,0,5,4,5,4,4,4
386,05-04-2025 19:03,30,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,2000,10000,5,5,4,3,3,5
387,05-04-2025 19:09,37,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,20000,15000,5,4,4,1,1,5
388,05-04-2025 19:11,27,NaN,San Fernando,No,0,Casa de amigos o familiares,5000,0,10000,0,5,4,4,3,3,5
389,05-04-2025 19:12,30,NaN,San Fernando,No,0,Casa de amigos o familiares,0,0,20000,0,5,5,3,3,5,5

In [157]:
vendimia.isnull().sum()

Marca temporal                                                                                          0
¿Cuál es su edad?                                                                                       0
¿Con qué género se identifica usted?                                                                  390
¿En qué comuna reside actualmente?                                                                      0
Alojamiento y estadía                                                                                   0
Responda esta pregunta solo si en la anterior seleccionó “Sí”.                                          0
¿Qué tipo de alojamiento utilizó?                                                                       0
Transporte: $                                                                                           0
Alojamiento: $                                                                                          0
Alimentación: $                                                                                         0
Compras (vino, recuerdos, artesanías): $                                                                0
Seguridad                                                                                               0
Limpieza                                                                                                0
Comodidad                                                                                               0
Programación artística                                                                                  0
Acceso a baños                                                                                          0
¿Estás de acuerdo con la afirmación: "La Vendimia refuerza la identidad cultural de San Fernando"?      0
dtype: int64

In [158]:
# La columna de genero tiene 390 nulos, significa que nadie respondio, entonces se elimina
vendimia = vendimia.drop(
columns=["¿Con qué género se identifica usted?"])

In [177]:
#Ahora veamos como se ve la columna de comunas donde reside
vendimia["¿En qué comuna reside actualmente?"].value_counts()

¿En qué comuna reside actualmente?
San Fernando        267
Santiago             17
Rancagua             11
Chimbarongo          10
Santa Cruz            8
Chimbarongo           5
Santiago              4
Rengo                 4
La Florida            4
Placilla              3
Nancagua              3
Metropolitana         2
Tinguiririca          2
Las condes            2
Talca                 2
San vicente           2
Curico                2
Providencia           2
Coquimbo              1
Coltauco              1
La cruz               1
Coltauco              1
Mostazal              1
Antofagasta           1
Santa Cruz            1
Lo barnechea          1
Pinto                 1
Marchigue             1
La Florida            1
San Bernardo          1
Maipu                 1
Estación central      1
Peñaloren             1
Doñihue               1
Talgante              1
Machali               1
Pichilemu             1
Limache               1
San juaquin           1
Graneros              1
Graneros              1
San miguel            1
Puente alto           1
Puente varas          1
Quilicura             1
Talagante             1
La florida            1
Renca                 1
Rancagua              1
San Vicente           1
Romeral               1
Chepica               1
Requinua              1
Peñalolen             1
Las cabras            1
Nancagua              1
Malloa                1
Iquique               1
Name: count, dtype: int64

In [178]:
vendimia["¿En qué comuna reside actualmente?"] = (vendimia["¿En qué comuna reside actualmente?"].str.strip())

In [179]:
vendimia["¿En qué comuna reside actualmente?"].value_counts()

¿En qué comuna reside actualmente?
San Fernando        267
Santiago             21
Chimbarongo          15
Rancagua             12
Santa Cruz            9
La Florida            5
Nancagua              4
Rengo                 4
Placilla              3
Coltauco              2
Metropolitana         2
Tinguiririca          2
Las condes            2
Talca                 2
San vicente           2
Curico                2
Providencia           2
Graneros              2
Coquimbo              1
La cruz               1
Mostazal              1
Antofagasta           1
Lo barnechea          1
Pinto                 1
Marchigue             1
San Bernardo          1
Maipu                 1
Estación central      1
Peñaloren             1
Doñihue               1
Talgante              1
Machali               1
Pichilemu             1
Limache               1
San juaquin           1
San miguel            1
Puente alto           1
Puente varas          1
Quilicura             1
Talagante             1
La florida            1
Renca                 1
San Vicente           1
Romeral               1
Chepica               1
Requinua              1
Peñalolen             1
Las cabras            1
Malloa                1
Iquique               1
Name: count, dtype: int64

In [180]:
vendimia["¿En qué comuna reside actualmente?"] = (vendimia["¿En qué comuna reside actualmente?"].str.strip())
vendimia["¿En qué comuna reside actualmente?"].value_counts().head(20)

¿En qué comuna reside actualmente?
San Fernando     267
Santiago          21
Chimbarongo       15
Rancagua          12
Santa Cruz         9
La Florida         5
Nancagua           4
Rengo              4
Placilla           3
Coltauco           2
Metropolitana      2
Tinguiririca       2
Las condes         2
Talca              2
San vicente        2
Curico             2
Providencia        2
Graneros           2
Coquimbo           1
La cruz            1
Name: count, dtype: int64

In [160]:
# La base de datos del censo, vienen en un excel en diferentes hojas, entonces se guardo la hoja que se va a usar en .csv.
# que quedo y se llamo poblacionporedad.

poblacion = pd.read_csv(
"datos/Poblacionporedad.csv",
sep=";",
encoding="utf-8-sig",
low_memory=False)
poblacion.head(40)

,Código región,Región,Código provincia,Provincia,Código comuna,Comuna,Grupos de edad,Población censada,Hombres,Mujeres,Razón hombre-mujer
0,0,País,0.0,País,0.0,País,Total País,18.480.432,8.967.033,9.513.399,"94,3"
1,0,País,0.0,País,0.0,País,0 a 4,870.693,443.028,427.665,"103,6"
2,0,País,0.0,País,0.0,País,5 a 9,1.147.515,584.218,563.297,"103,7"
3,0,País,0.0,País,0.0,País,10 a 14,1.256.440,641.284,615.156,"104,2"
4,0,País,0.0,País,0.0,País,15 a 19,1.219.347,625.986,593.361,"105,5"
5,0,País,0.0,País,0.0,País,20 a 24,1.273.193,646.831,626.362,"103,3"
6,0,País,0.0,País,0.0,País,25 a 29,1.383.669,693.829,689.840,"100,6"
7,0,País,0.0,País,0.0,País,30 a 34,1.527.489,758.913,768.576,"98,7"
8,0,País,0.0,País,0.0,País,35 a 39,1.408.198,692.292,715.906,"96,7"
9,0,País,0.0,País,0.0,País,40 a 44,1.270.493,615.866,654.627,"94,1"
10,0,País,0.0,País,0.0,País,45 a 49,1.151.776,549.508,602.268,"91,2"
11,0,País,0.0,País,0.0,País,50 a 54,1.173.352,556.491,616.861,"90,2"
12,0,País,0.0,País,0.0,País,55 a 59,1.133.239,530.699,602.540,"88,1"
13,0,País,0.0,País,0.0,País,60 a 64,1.077.790,501.042,576.748,"86,9"
14,0,País,0.0,País,0.0,País,65 a 69,870.801,403.425,467.376,"86,3"
15,0,País,0.0,País,0.0,País,70 a 74,646.241,292.622,353.619,"82,8"
16,0,País,0.0,País,0.0,País,75 a 79,477.186,208.574,268.612,"77,6"
17,0,País,0.0,País,0.0,País,80 a 84,317.424,129.155,188.269,"68,6"
18,0,País,0.0,País,0.0,País,85 o más,275.586,93.270,182.316,"51,2"
19,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,Total Comuna,241.653,118.844,122.809,"96,8"
20,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,0 a 4,12.671,6.321,6.350,"99,5"
21,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,5 a 9,16.246,8.264,7.982,"103,5"
22,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,10 a 14,18.634,9.543,9.091,105
23,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,15 a 19,17.062,8.705,8.357,"104,2"
24,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,20 a 24,17.872,9.194,8.678,"105,9"
25,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,25 a 29,19.202,9.839,9.363,"105,1"
26,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,30 a 34,19.568,9.999,9.569,"104,5"
27,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,35 a 39,18.784,9.526,9.258,"102,9"
28,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,40 a 44,16.548,8.029,8.519,"94,2"
29,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,45 a 49,14.675,7.152,7.523,"95,1"
30,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,50 a 54,15.123,7.218,7.905,"91,3"
31,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,55 a 59,12.589,5.844,6.745,"86,6"
32,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,60 a 64,12.043,5.461,6.582,83
33,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,65 a 69,10.067,4.858,5.209,"93,3"
34,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,70 a 74,7.850,3.599,4.251,"84,7"
35,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,75 a 79,5.890,2.642,3.248,"81,3"
36,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,80 a 84,3.785,1.596,2.189,"72,9"
37,15,Arica y Parinacota,151.0,Arica,15101.0,Arica,85 o más,3.044,1.054,1.990,53
38,15,Arica y Parinacota,151.0,Arica,15102.0,Camarones,Total Comuna,861,430,431,"99,8"
39,15,Arica y Parinacota,151.0,Arica,15102.0,Camarones,0 a 4,26,17,9,"188,9"

In [161]:
poblacion.shape

(6596, 11)

In [162]:
print (poblacion.columns.tolist())
poblacion.info()

['Código región', 'Región', 'Código provincia', 'Provincia', 'Código comuna', 'Comuna', 'Grupos de edad', 'Población censada', 'Hombres', 'Mujeres', 'Razón hombre-mujer']
<class 'pandas.DataFrame'>
RangeIndex: 6596 entries, 0 to 6595
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Código región       6594 non-null   str
 1   Región              6593 non-null   str
 2   Código provincia    6593 non-null   float64
 3   Provincia           6593 non-null   str
 4   Código comuna       6593 non-null   float64
 5   Comuna              6593 non-null   str
 6   Grupos de edad      6593 non-null   str
 7   Población censada   6593 non-null   str
 8   Hombres             6593 non-null   str
 9   Mujeres             6593 non-null   str
 10  Razón hombre-mujer  6593 non-null   str
dtypes: float64(2), str(9)
memory usage: 567.0 KB

In [163]:
#Colocar el nombre a la tabla "viajes-ocasionales-6"
viajes = pd.read_csv(
"datos/Viajes-ocasionales-6.csv",
sep=";",
encoding="latin1",
low_memory=False)

viajes.head(10)

,CUT Comuna Origen,Comuna Origen,CUT Provincia Origen,Provincia Origen,CUT Región Origen,Región Origen,CUT Comuna Destino,Comuna Destino,Destino Turístico,CUT Provincia Destino,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,1101,Iquique,11,Iquique,1,Tarapacá,1402,Camiña,Camiña,14,...,"33,643461227417","105,965751409531","99,9849243164062","14,9766898155212","25,7534079551697","25,3820378780365","117,386157989502","145,944531440735","44,3386154174805","64,348644733429"
1,1101,Iquique,11,Iquique,1,Tarapacá,1403,Colchane,Colchane - P.N. Volcán Isluga,14,...,"110,10587310791","139,269273281097","99,9849243164062","68,8927731513977","168,827896595001","157,932680130005","262,7214012146","131,911403417587","160,727480888367","436,451677322388"
2,1101,Iquique,11,Iquique,1,Tarapacá,1404,Huara,Resto región Tarapacá,14,...,"1064,35677337646","2086,01150631905","1521,64556694031","973,484838008881","1573,81937503815","6449,85784745216","1900,53779602051","1299,46765494347","1144,49051046371","1421,26571846008"
3,1101,Iquique,11,Iquique,1,Tarapacá,1405,Pica,Pica,14,...,"932,841424942017","1653,06572198868","1568,51350021362","934,545444488525","1485,11319208145","1613,16951847076","2495,8533115387","1403,31280231476","1629,44411659241","2039,57226133347"
4,1101,Iquique,11,Iquique,1,Tarapacá,2101,Antofagasta,Antofagasta,21,...,"899,1979637146","1068,74029278755","1849,72109985352","748,834490776062","1115,98101139069","1644,19200921059","1771,97200393677","1465,05856561661","1199,91377973557","1631,09825563431"
5,1101,Iquique,11,Iquique,1,Tarapacá,2102,Mejillones,Mejillones,21,...,"247,738214492798","214,959095716476","299,954772949219","284,557106494904","185,996835231781","245,359699487686","265,516309738159","286,275811672211","210,608423233032","282,574483394623"
6,1101,Iquique,11,Iquique,1,Tarapacá,2103,Sierra Gorda,Resto región Antofagasta,21,...,"30,5849647521973","75,689822435379","59,3660488128662","17,9720277786255","57,2297954559326","39,4831700325012","64,2828960418701","75,7788913249969","47,109778881073","53,157576084137"
7,1101,Iquique,11,Iquique,1,Tarapacá,2104,Taltal,Taltal,21,...,"21,4094753265381","45,4138934612274","87,4868087768555","53,9160833358765","220,334712505341","45,1236228942871","103,411615371704","115,07164978981","44,3386154174805","64,348644733429"
8,1101,Iquique,11,Iquique,1,Tarapacá,2201,Calama,Calama - Alto El Loa,22,...,"437,364995956421","481,387270689011","578,037843704224","509,207453727722","4432,44765806198","256,640605211258","422,031187057495","451,866722345352","526,521058082581","867,307820320129"
9,1101,Iquique,11,Iquique,1,Tarapacá,2202,Ollagüe,Resto región Antofagasta,22,...,0,"6,05518579483032",0,0,0,"8,46067929267883",0,0,0,0

In [164]:
viajes.shape

(649393, 26)

In [165]:
viajes.info()

<class 'pandas.DataFrame'>
RangeIndex: 649393 entries, 0 to 649392
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CUT Comuna Origen      649393 non-null  int64
 1   Comuna Origen          649393 non-null  str
 2   CUT Provincia Origen   649393 non-null  int64
 3   Provincia Origen       649393 non-null  str
 4   CUT Región Origen      649393 non-null  int64
 5   Región Origen          649393 non-null  str
 6   CUT Comuna Destino     649393 non-null  int64
 7   Comuna Destino         649393 non-null  str
 8   Destino Turístico      649393 non-null  str
 9   CUT Provincia Destino  649393 non-null  int64
 10  Provincia Destino      649393 non-null  str
 11  CUT Región Destino     649393 non-null  int64
 12  Región Destino         649393 non-null  str
 13  Anio                   649393 non-null  int64
 14  Enero                  648801 non-null  str
 15  Febrero                649133 non-null  str
 16  Marzo                  649125 non-null  str
 17  Abril                  649215 non-null  str
 18  Mayo                   649231 non-null  str
 19  Junio                  649070 non-null  str
 20  Julio                  649006 non-null  str
 21  Agosto                 649141 non-null  str
 22  Septiembre             649034 non-null  str
 23  Octubre                649149 non-null  str
 24  Noviembre              648988 non-null  str
 25  Diciembre              648572 non-null  str
dtypes: int64(7), str(19)
memory usage: 128.8 MB

In [166]:
viajes.columns

Index(['CUT Comuna Origen', 'Comuna Origen', 'CUT Provincia Origen',
       'Provincia Origen', 'CUT Región Origen', 'Región Origen',
       'CUT Comuna Destino', 'Comuna Destino', 'Destino Turístico',
       'CUT Provincia Destino', 'Provincia Destino', 'CUT Región Destino',
       'Región Destino', 'Anio', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo',
       'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre',
       'Diciembre'],
      dtype='str')

In [167]:
# Valores faltantes
viajes.isna().sum().sort_values(ascending=False)

Diciembre                821
Enero                    592
Noviembre                405
Julio                    387
Septiembre               359
Junio                    323
Marzo                    268
Febrero                  260
Agosto                   252
Octubre                  244
Abril                    178
Mayo                     162
CUT Provincia Destino      0
Destino Turístico          0
Región Origen              0
CUT Región Origen          0
Provincia Origen           0
CUT Provincia Origen       0
Comuna Origen              0
CUT Comuna Origen          0
Comuna Destino             0
CUT Comuna Destino         0
Provincia Destino          0
CUT Región Destino         0
Región Destino             0
Anio                       0
dtype: int64

In [168]:
# Registros duplicados
viajes.duplicated().sum()

np.int64(0)

De la tabla de viajes

Las relevantes en este 'Comuna Origen', 'Comuna Destino' 'Anio',  'Mayo'. Porque son este, porque vamos a ver los viajes de mayo del año 2025, de cualquier comuna de origen a la comuna de destino San Fernando.

In [169]:
print(viajes.columns.tolist())
viajes_mayo_años = viajes[['Comuna Origen', 'Comuna Destino', 'Anio', 'Mayo']]
viajes_mayo_años.head()

['CUT Comuna Origen', 'Comuna Origen', 'CUT Provincia Origen', 'Provincia Origen', 'CUT Región Origen', 'Región Origen', 'CUT Comuna Destino', 'Comuna Destino', 'Destino Turístico', 'CUT Provincia Destino', 'Provincia Destino', 'CUT Región Destino', 'Región Destino', 'Anio', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

  Comuna Origen Comuna Destino  Anio              Mayo
0       Iquique         Camiña  2019  99,9849243164062
1       Iquique       Colchane  2019  99,9849243164062
2       Iquique          Huara  2019  1521,64556694031
3       Iquique           Pica  2019  1568,51350021362
4       Iquique    Antofagasta  2019  1849,72109985352

In [170]:
#Como se ve los datos de ACT, que son los de actividades a nivel nacional, pero los datos sacados de SERNATUR, vienen en un 
# excel, de distintas hojas, se busco la hoja de las actividades a nivel comunal y los valores en UF, y se guardo de forma .csv 

#
ventas = pd.read_csv(
"datos/Ventas_UF_comuna_ACT.csv",
sep=";",
encoding="utf-8-sig",
low_memory=False
)

ventas.head(20)

,Región / CUT Comuna,Nombre Comuna / ACT,2005,2006,2007,2008,2009,2010,2011,2012,...,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total nacional,NaN,424.743.716,468.420.220,554.824.398,631.450.479,653.457.736,601.817.095,718.437.783,724.226.070,...,"34,30%","43,30%","16,80%","-4,70%","-3,50%","-28,80%","-11,40%","23,10%","13,10%","-11,90%"
2,Alojamiento turístico,NaN,15.531.510,16.852.842,23.156.105,27.979.585,27.259.802,54.478.438,33.255.887,39.709.942,...,"478,20%","-4,20%","-3,20%","-87,80%","87,10%","3,60%","-43,40%","33,80%","38,90%","23,90%"
3,Actividades de provisión de alimentos y bebidas,NaN,74.889.299,80.493.609,72.998.468,75.088.720,151.258.139,86.940.135,97.963.381,92.123.423,...,"2,70%","26,60%","26,20%","7,30%","8,40%","12,20%","-30,10%","44,30%","16,10%","5,10%"
4,Transporte de pasajeros por ferrocarril,NaN,*,*,*,*,*,*,*,*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Transporte de pasajeros por carretera,NaN,12.475.529,18.220.675,27.172.877,31.082.665,30.189.444,32.500.408,75.443.203,59.098.724,...,"60,20%","-32,10%","-13,80%","4,40%","-8,80%","12,60%","-11,40%","21,90%","10,40%","9,60%"
6,Transporte de pasajeros por agua,NaN,44.373.897,46.623.772,49.536.328,109.895.836,31.522.524,32.588.551,19.430.506,27.677.181,...,"9,10%","6,30%","-30,40%","-87,80%","-30,70%","94,70%","-51,20%","-5,40%","30,70%","-6,20%"
7,Transporte aéreo de pasajeros,NaN,19.599.329,29.326.088,94.827.033,118.343.062,25.336.496,30.709.073,40.526.213,37.409.819,...,"2,20%","-2,20%","-57,80%","-66,60%","181,20%","69,10%","303,80%","-87,40%","1781,90%","-73,20%"
8,Alquiler de equipos de transporte,NaN,9.668.049,14.255.406,10.598.580,10.998.989,77.841.241,89.425.576,102.117.403,145.924.639,...,"7,70%","32,60%","15,10%","-58,60%","8,70%","-42,80%","-17,40%","12,00%","0,00%","12,40%"
9,Actividades de agencias de viajes y de otros s...,NaN,40.817.257,44.702.846,36.160.396,25.444.621,23.725.014,25.064.513,25.904.496,38.579.851,...,"12,50%","25,50%","-52,60%","24,50%","530,90%","-83,00%","-52,90%","-1,20%","90,70%","10,10%"
10,Actividades culturales,NaN,886.570,1.177.505,1.328.200,1.316.704,1.189.747,1.625.322,2.396.465,1.770.825,...,"-8,00%","353,70%","28,90%","3,00%","-6,50%","-11,60%","-55,50%","6,60%","132,20%","29,30%"
11,Actividades deportivas y recreativas,NaN,7.245.497,8.489.993,1.868.109,1.938.952,2.390.292,2.768.437,3.309.193,2.999.726,...,"27,70%","517,80%","-12,00%","10,60%","2,40%","-13,50%","-57,30%","24,30%","74,00%","8,80%"
12,Comercio al por menor de bienes característico...,NaN,1.795.140,2.168.336,1.571.896,1.556.749,1.635.048,1.705.045,1.834.430,2.087.929,...,"9,80%","32,70%","37,10%","-21,80%","-33,60%","-21,00%","-36,80%","44,40%","9,40%","-2,90%"
13,Actividades relacionadas con segundos hogares ...,NaN,197.461.639,206.109.148,235.606.405,227.804.594,281.109.990,244.011.596,316.256.608,276.844.009,...,"6,40%","103,10%","33,20%","21,40%","-19,70%","-32,50%","-8,40%","33,90%","-13,50%","-9,40%"
14,Región de Tarapacá,NaN,3.625.196,3.960.751,4.057.865,4.965.369,5.030.948,5.336.401,6.241.810,6.490.654,...,"37,50%","18,20%","8,10%","6,10%","6,50%","-7,00%","-14,80%","-3,90%","19,60%","14,90%"
15,1101,Iquique,3.498.836,3.831.622,3.947.261,4.858.741,4.828.127,5.205.630,5.848.072,6.015.605,...,"40,30%","15,60%","3,90%","2,30%","12,90%","-8,10%","-16,20%","-8,90%","17,50%","10,10%"
16,NaN,Alojamiento turístico,326.495,325.983,378.884,434.652,411.323,460.990,617.621,651.209,...,"132,20%","-65,60%","20,10%","7,20%","-8,00%","60,40%","7,30%","50,60%","23,00%","49,20%"
17,NaN,Actividades de provisión de alimentos y bebidas,666.876,829.659,875.280,929.165,1.027.244,1.084.570,1.279.715,1.374.040,...,"12,10%","31,00%","6,00%","-3,90%","9,10%","4,90%","-46,00%","81,40%","26,60%","1,50%"
18,NaN,Transporte de pasajeros por ferrocarril,0,0,0,0,*,*,*,*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Transporte de pasajeros por carretera,228.379,257.096,409.167,360.986,366.669,515.467,768.183,1.133.823,...,"49,80%","-11,80%","-24,80%","-4,60%","23,80%","4,90%","-15,20%","12,40%","-22,10%","47,90%"

In [171]:
ventas.shape

(4549, 40)

In [172]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 4549 entries, 0 to 4548
Data columns (total 40 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Región / CUT Comuna   383 non-null    str
 1    Nombre Comuna / ACT  4511 non-null   str
 2   2005                  4541 non-null   str
 3   2006                  4541 non-null   str
 4   2007                  4541 non-null   str
 5   2008                  4541 non-null   str
 6   2009                  4541 non-null   str
 7   2010                  4541 non-null   str
 8   2011                  4541 non-null   str
 9   2012                  4541 non-null   str
 10  2013                  4541 non-null   str
 11  2014                  4541 non-null   str
 12  2015                  4541 non-null   str
 13  2016                  4541 non-null   str
 14  2017                  4541 non-null   str
 15  2018                  4541 non-null   str
 16  2019                  4541 non-null   str
 17  2020                  4541 non-null   str
 18  2021                  4541 non-null   str
 19  2022                  4541 non-null   str
 20  2023                  4541 non-null   str
 21  Unnamed: 21           0 non-null      float64
 22  2006.1                1201 non-null   str
 23  2007.1                1209 non-null   str
 24  2008.1                1199 non-null   str
 25  2009.1                1204 non-null   str
 26  2010.1                1222 non-null   str
 27  2011.1                1228 non-null   str
 28  2012.1                1250 non-null   str
 29  2013.1                1290 non-null   str
 30  2014.1                1295 non-null   str
 31  2015.1                1346 non-null   str
 32  2016.1                1591 non-null   str
 33  2017.1                1672 non-null   str
 34  2018.1                1709 non-null   str
 35  2019.1                1733 non-null   str
 36  2020.1                1715 non-null   str
 37  2021.1                1685 non-null   str
 38  2022.1                1699 non-null   str
 39  2023.1                1723 non-null   str
dtypes: float64(1), str(39)
memory usage: 1.4 MB

In [173]:
# Como se ven los datos no sirven para ser ocupados, ya que las columnas son las columnas, y en las filas se encuentran las 
# comunas y en suborden las actividades. Entonces, se va a realizar una tabla con solo los datos de San fernando. 
# Primero se va mirar como va quedar la tabla son con las columnas que se van a ocupar. 
print(ventas.columns.tolist())
ventas_2023 = ventas[['Región / CUT Comuna ', ' Nombre Comuna / ACT', '2023']]
ventas_2023.head(20)

['Región / CUT Comuna ', ' Nombre Comuna / ACT', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'Unnamed: 21', '2006.1', '2007.1', '2008.1', '2009.1', '2010.1', '2011.1', '2012.1', '2013.1', '2014.1', '2015.1', '2016.1', '2017.1', '2018.1', '2019.1', '2020.1', '2021.1', '2022.1', '2023.1']

,Región / CUT Comuna,Nombre Comuna / ACT,2023
0,NaN,NaN,NaN
1,Total nacional,NaN,1.240.313.841
2,Alojamiento turístico,NaN,63.769.559
3,Actividades de provisión de alimentos y bebidas,NaN,275.002.546
4,Transporte de pasajeros por ferrocarril,NaN,*
5,Transporte de pasajeros por carretera,NaN,85.134.213
6,Transporte de pasajeros por agua,NaN,1.839.638
7,Transporte aéreo de pasajeros,NaN,53.915.118
8,Alquiler de equipos de transporte,NaN,51.820.932
9,Actividades de agencias de viajes y de otros s...,NaN,28.278.072
10,Actividades culturales,NaN,16.022.158
11,Actividades deportivas y recreativas,NaN,16.624.125
12,Comercio al por menor de bienes característico...,NaN,1.979.553
13,Actividades relacionadas con segundos hogares ...,NaN,645.927.926
14,Región de Tarapacá,NaN,16.290.283
15,1101,Iquique,12.982.713
16,NaN,Alojamiento turístico,2.840.784
17,NaN,Actividades de provisión de alimentos y bebidas,3.239.109
18,NaN,Transporte de pasajeros por ferrocarril,0
19,NaN,Transporte de pasajeros por carretera,1.599.461

In [174]:
#Luego se va a realizar la tabla solo de la comuna de San Fernando.
sf=ventas[ventas.iloc[:,1].astype(str).str.contains("San Fernando", case=False, na=False)]
indice_sf = sf.index[0]

sft = ventas.iloc[indice_sf+1:indice_sf+13, [1,2]]
sft.columns = ["Actividad", "Ventas_2023"]
print(sft)

                                              Actividad Ventas_2023
1334                              Alojamiento turístico       9.648
1335    Actividades de provisión de alimentos y bebidas     176.741
1336            Transporte de pasajeros por ferrocarril           *
1337              Transporte de pasajeros por carretera      27.475
1338                   Transporte de pasajeros por agua           *
1339                      Transporte aéreo de pasajeros           0
1340                  Alquiler de equipos de transporte           *
1341  Actividades de agencias de viajes y de otros s...           *
1342                             Actividades culturales           *
1343               Actividades deportivas y recreativas           *
1344  Comercio al por menor de bienes característico...       3.565
1345  Actividades relacionadas con segundos hogares ...     134.509

In [175]:
sft.isna().sum().sort_values(ascending=False)

Actividad      0
Ventas_2023    0
dtype: int64

In [ ]:
print ("startup")